---
- hosts: all

  tasks:
    - name: get hostname
      ansible.builtin.shell: hostname
      args:
        executable: /bin/bash
      changed_when: false
      register: hostname
    - name: get uptime
      ansible.builtin.shell: uptime
      args:
        executable: /bin/bash
      changed_when: false
      register: uptime
    - debug: var={{ item }}
      with_items:
        - hostname.stdout
        - uptime.stdout
